### ISSUE TITLE
Is this supposed to seed to web clients?

### ISSUE THREAD

**Issue by Ciao121** [pldubouilh/webtorrent-webui#1]
As title, because I tried but it was not seeding.
Thank you!

**Comment by pldubouilh** [comment]
Hey !
No support for seeding to webclients at the moment as it's using plain `webtorrent`. 
Maybe we could run `webtorrent-hybrid`, but then it'll require XVFB on headless environments. 
Interesting, will have a look into it.

**Comment by Ciao121** [comment]
Thanks for your answer!

**Comment by pldubouilh** [comment]
@Ciao121 @zzoozzo1122 alright, now a [webtorrent-hybrid fueled version](https://github.com/pldubouilh/webtorrent-webui-hybrid) of webtorrent-webui exists !
Just install with `npm i -g webtorrent-webui-hybrid` :+1:
