### ISSUE TITLE
Tracker (wss://) did not work. Can you help me?

### ISSUE THREAD

**Issue by samurai815** [pldubouilh/webtorrent-webui#15]
I do not know if I did something wrong but when I seed by webtorrent-webui tracker (wss://) did not work and I could not find seed peer
I tried open tracker "wss://tracker.openwebtorrent.com", "wss://tracker.btorrent.xyz", "wss://tracker.fastcast.nz"
Can you help me? Thank you.

**Comment by samurai815** [comment]
Hello, Can anyone help me?

**Comment by pldubouilh** [comment]
Hi, `wss` trackers are for webtorrent-hybrid. Have a look at [webtorrent-webui-hybrid](https://github.com/pldubouilh/webtorrent-webui-hybrid)
