### ISSUE TITLE
webtorrent hybrid question.

### ISSUE THREAD

**Issue by zzoozzo1122** [pldubouilh/webtorrent-webui#7]
Normal installation 
Only downloaded, not uploaded.

https://github.com/pldubouilh/webtorrent-webui/pull/3
https://github.com/pldubouilh/webtorrent-webui/pull/3/commits/c37e41349a92e80e0a486769345ee740e5c753f3

index.js, lib/handlerWebtorrent.js ,package.json

After modifying the 3 files npm install started
However, the file is not changed.
Does not appear to be changed file.
Can you install the program in an easy way?

Place the  (. torrent_folder) file in the folder. 
Do I have to start a program every time?
Can I update it automatically?

**Comment by pldubouilh** [comment]
Closing for #1
