### ISSUE TITLE
webtorrent-webui ver, 0.0.11 +webtorrent-hybrid ,Ask how to enable

### ISSUE THREAD

**Issue by zzoozzo1122** [pldubouilh/webtorrent-webui#9]
https://github.com/pldubouilh/webtorrent-webui/pull/3/commits/c37e41349a92e80e0a486769345ee740e5c753f3

The existing method is ver.0.0.7.
How do I apply to the new version? ?

The above use methods are not applicable due to their low version.
Please add a file to activate the seed.

package.json , index.js ,  lib/handlerWebtorrent.js 

Please tell me how I can modify three files.

**Comment by pldubouilh** [comment]
Hi, I'll make a proper repo for webtorrent-webui-hybrid soon, so I'll close this one, please check #1 for feedback
